export const IPC = {
  // ── 游戏管理 ──
  GAME_LOAD: "game:load",
  GAME_REMOVE: "game:remove",
  GAME_LAUNCH: "game:launch",
  GAME_GET_RUNNING_IDS: "game:getRunningIds",
  GAME_GET_ALL: "game:getAll",
  GAME_GET_RECORDS: "game:getRecords",
  GAME_GET_COVER: "game:getCover",
  GAME_GET_VIDEO: "game:getVideo",
  GAME_GET_ICON: "game:getIcon",
  GAME_GET_ACHIEVEMENT_ICON: "game:getAchievementIcon",
  GAME_GET_VERSIONS: "game:getVersions",
  GAME_GET_INSTALL_PATH: "game:getInstallPath",
  GAME_GET_MANIFEST: "game:getManifest",
  GAME_UNLOCK_ACHIEVEMENT: "game:unlockAchievement",
  GAME_TOGGLE_FAVORITE: "game:toggleFavorite",
  GAME_REORDER: "game:reorder",
  GAME_PREPARE_IMPORT: "game:prepareImport",
  GAME_LOAD_WITH_MANIFEST: "game:loadWithManifest",
  GAME_CHECK_ID_EXISTS: "game:checkIdExists",
  GAME_SELECT_IMPORT_DIRECTORY: "game:selectImportDirectory",
  GAME_START_IMPORT: "game:startImport",
  GAME_GET_IMPORT_TASKS: "game:getImportTasks",
  GAME_CANCEL_IMPORT: "game:cancelImport",
  GAME_RETRY_IMPORT: "game:retryImport",
  GAME_DISMISS_IMPORT: "game:dismissImport",
  GAME_IMPORT_EVENT: "game:import:event",

  // ── 游戏市场 ──
  MARKET_GET_SOURCES: "market:getSources",
  MARKET_OPEN_GAME_HOSTING: "market:openGameHosting",
  MARKET_GET_INDEX: "market:getIndex",
  MARKET_GET_CACHED_IMAGE: "market:getCachedImage",
  MARKET_DOWNLOAD_AND_INSTALL: "market:downloadAndInstall",
  MARKET_GET_TASK_STATE: "market:getTaskState",
  MARKET_CANCEL_TASK: "market:cancelTask",
  MARKET_DISMISS_TASK: "market:dismissTask",
  MARKET_PAUSE_TASK: "market:pauseTask",
  MARKET_RESUME_TASK: "market:resumeTask",
  MARKET_GET_PENDING_TASKS: "market:getPendingTasks",
  MARKET_RESOLVE_ASSET_INFO: "market:resolveAssetInfo",

  // ── 房间管理 ──
  ROOM_CREATE: "room:create",
  ROOM_JOIN: "room:join",
  ROOM_LEAVE: "room:leave",
  ROOM_READY: "room:ready",
  ROOM_UNREADY: "room:unready",
  ROOM_START: "room:start",
  ROOM_SET_ADDRESS: "room:setAddress",
  ROOM_SET_PASSWORD: "room:setPassword",
  ROOM_GET_STATE: "room:getState",
  ROOM_SEND_CHAT: "room:sendChat",
  ROOM_KICK_PLAYER: "room:kickPlayer",
  ROOM_RECONNECT: "room:reconnect",
  ROOM_DISCOVER_LAN: "room:discoverLan",
  ROOM_DISCOVER_VIRTUAL_LAN: "room:discoverVirtualLan",
  ROOM_DISCOVER_RELAY: "room:discoverRelay",
  ROOM_MEASURE_RELAY_LATENCY: "room:measureRelayLatency",
  ROOM_VALIDATE_DISCOVERED: "room:validateDiscovered",
  ROOM_PROBE_PASSWORD: "room:probePassword",
  ROOM_SET_DIRECT_HOST_MODE: "room:setDirectHostMode",
  ROOM_ENABLE_RELAY_HOST: "room:enableRelayHost",
  ROOM_DISABLE_RELAY_HOST: "room:disableRelayHost",

  // ── 房间事件推送（主→渲染，使用 ipcRenderer.on）──
  ROOM_EVENT: "room:event",

  // ── 聊天弹出窗口 ──
  ROOM_POP_OUT_CHAT: "room:popOutChat",
  ROOM_POP_IN_CHAT: "room:popInChat",
  ROOM_CHAT_WINDOW_CLOSED: "room:chatWindowClosed",
  ROOM_GET_CHAT_HISTORY: "room:getChatHistory",

  // ── 游戏进程事件（主→渲染）──
  GAME_PROCESS_STARTED: "game:process:started",
  GAME_PROCESS_ENDED: "game:process:ended",
  GAME_LAUNCH_FAILED: "game:launch:failed",
  MARKET_EVENT: "market:event",
  MARKET_FLOAT_BALL_EVENT: "market:floatBall:event",
  MARKET_GET_ALL_TASK_STATES: "market:getAllTaskStates",
  FLOAT_BALL_DRAG_STATE: "floatBall:dragState",

  // ── 系统 ──
  SYSTEM_GET_SETTINGS: "system:getSettings",
  SYSTEM_GET_APP_VERSION: "system:getAppVersion",
  SYSTEM_GET_SENSITIVE_WORDS: "system:getSensitiveWords",
  SYSTEM_CLOUD_GET_LOCAL_STATUS: "system:cloud:getLocalStatus",
  SYSTEM_CLOUD_GET_PRESENCE_STATUS: "system:cloud:getPresenceStatus",
  SYSTEM_CLOUD_SET_PRESENCE: "system:cloud:setPresence",
  SYSTEM_CLOUD_PRESENCE_CHANGED: "system:cloud:presenceChanged",
  SYSTEM_CLOUD_GET_SNAPSHOT_META: "system:cloud:getSnapshotMeta",
  SYSTEM_CLOUD_LOGIN_GITHUB: "system:cloud:loginGithub",
  SYSTEM_CLOUD_UPLOAD: "system:cloud:upload",
  SYSTEM_CLOUD_DOWNLOAD: "system:cloud:download",
  SYSTEM_CLOUD_SYNC_EVENT: "system:cloud:sync:event",
  SYSTEM_CLOUD_AUTH_CHANGED: "system:cloud:authChanged",
  SYSTEM_FEEDBACK_SELECT_IMAGES: "system:feedback:selectImages",
  SYSTEM_FEEDBACK_RELEASE_IMAGES: "system:feedback:releaseImages",
  SYSTEM_FEEDBACK_SUBMIT: "system:feedback:submit",
  SYSTEM_FEEDBACK_GET_HISTORY: "system:feedback:getHistory",
  SYSTEM_FEEDBACK_GET_DETAIL: "system:feedback:getDetail",
  // ── 论坛 ──
  FORUM_SELECT_IMAGES: "forum:selectImages",
  FORUM_RELEASE_IMAGES: "forum:releaseImages",
  FORUM_GET_SEARCH_AVAILABILITY: "forum:getSearchAvailability",
  FORUM_LIST_POSTS: "forum:listPosts",
  FORUM_GET_POST: "forum:getPost",
  FORUM_GET_COMMENTS: "forum:getComments",
  FORUM_CREATE_POST: "forum:createPost",
  FORUM_CREATE_COMMENT: "forum:createComment",
  FORUM_DELETE_POST: "forum:deletePost",
  FORUM_DELETE_COMMENT: "forum:deleteComment",
  FORUM_LIKE_POST: "forum:likePost",
  FORUM_UNLIKE_POST: "forum:unlikePost",
  FORUM_LIKE_COMMENT: "forum:likeComment",
  FORUM_UNLIKE_COMMENT: "forum:unlikeComment",
  SYSTEM_SAVE_SETTINGS: "system:saveSettings",
  SYSTEM_SAVE_PARTIAL_SETTINGS: "system:savePartialSettings",
  SYSTEM_SET_IGNORED_UPDATE_VERSION: "system:setIgnoredUpdateVersion",
  SYSTEM_UPLOAD_AVATAR: "system:uploadAvatar",
  SYSTEM_SELECT_GAME_STORAGE_PATH: "system:selectGameStoragePath",
  SYSTEM_SELECT_GAME_STORAGE_PATH_RELAXED:
    "system:selectGameStoragePathRelaxed",
  SYSTEM_GET_DEFAULT_GAMES_MIGRATION_STATUS:
    "system:getDefaultGamesMigrationStatus",
  SYSTEM_GET_GAME_STORAGE_PATHS: "system:getGameStoragePaths",
  SYSTEM_ADD_GAME_STORAGE_PATH: "system:addGameStoragePath",
  SYSTEM_SET_DEFAULT_GAME_STORAGE_PATH: "system:setDefaultGameStoragePath",
  SYSTEM_MIGRATE_DEFAULT_GAMES_LIBRARY: "system:migrateDefaultGamesLibrary",
  SYSTEM_MIGRATE_GAME_STORAGE_LIBRARY: "system:migrateGameStorageLibrary",
  SYSTEM_OPEN_PATH: "system:openPath",
  SYSTEM_OPEN_URL: "system:openUrl",
  SYSTEM_REMOVE_GAME_STORAGE_PATH: "system:removeGameStoragePath",
  SYSTEM_UNINSTALL: "system:uninstall",
  SYSTEM_GET_USER_DATA: "system:getUserData",
  SYSTEM_CHECK_IN: "system:checkIn",
  SYSTEM_UNLOCK_FRAME: "system:unlockFrame",
  SYSTEM_SAVE_NICKNAME_STYLE: "system:saveNicknameStyle",
  SYSTEM_EQUIP_FRAME: "system:equipFrame",
  SYSTEM_UNEQUIP_FRAME: "system:unequipFrame",
  SYSTEM_GET_AVATAR_FRAME_IMAGE: "system:getAvatarFrameImage",
  SYSTEM_UNLOCK_GAME_CARD_PRODUCT: "system:unlockGameCardProduct",
  SYSTEM_GET_GAME_CARD_PRODUCT_PROGRESS: "system:getGameCardProductProgress",
  SYSTEM_EQUIP_GAME_CARD_PRODUCT: "system:equipGameCardProduct",
  SYSTEM_UNEQUIP_GAME_CARD_PRODUCT: "system:unequipGameCardProduct",
  SYSTEM_GET_GAME_CARD_PRODUCT_IMAGE: "system:getGameCardProductImage",
  SYSTEM_DATA_HEALTH_CHECK: "system:dataHealthCheck",
  SYSTEM_CHECK_UPDATE: "system:checkUpdate",
  SYSTEM_DOWNLOAD_UPDATE: "system:downloadUpdate",
  SYSTEM_INSTALL_UPDATE: "system:installUpdate",
  SYSTEM_GET_UPDATE_STATUS: "system:getUpdateStatus",
  SYSTEM_UPDATE_EVENT: "system:update:event",
  SYSTEM_CLEAR_CACHE: "system:clearCache",
  SYSTEM_LOG_ERROR: "system:log:error",
  SYSTEM_SAVE_PNG: "system:savePng",
  // ── 游戏数据存储 (Preload → Main) ──
  GAME_STORAGE_INIT: "game:storage:init",
  GAME_STORAGE_SAVE: "game:storage:save",
  GAME_STORAGE_REMOVE: "game:storage:remove",
  GAME_STORAGE_CLEAR: "game:storage:clear",
  GAME_STORAGE_FLUSH: "game:storage:flush",

  // ── 统计 ──
  STATS_GET_DAILY_PLAY_DURATIONS: "stats:getDailyPlayDurations",
  STATS_GET_RECENT_SESSIONS: "stats:getRecentSessions",
  STATS_GET_SESSIONS_BY_DATE: "stats:getSessionsByDate",
} as const;
