export const config = {
  PORT: Number(process.env.PORT || 38090),
  ROOM_TTL_MS: Number(process.env.ROOM_TTL_MS || 60000),
  HEARTBEAT_INTERVAL_MS: Number(process.env.HEARTBEAT_INTERVAL_MS || 30000),
  MAX_TEXT_BYTES: Number(process.env.MAX_TEXT_BYTES || 1024 * 1024),
  MAX_BINARY_BYTES: Number(process.env.MAX_BINARY_BYTES || 12 * 1024 * 1024),
  MAX_CLOUD_FILE_BYTES: Number(process.env.MAX_CLOUD_FILE_BYTES || 64 * 1024 * 1024),
  RELAY_TOKEN: (process.env.RELAY_TOKEN || "").trim(),
  MAX_ROOMS: Number(process.env.MAX_ROOMS || 80),
  MAX_CLIENTS: Number(process.env.MAX_CLIENTS || 400),
  MAX_CLIENTS_PER_ROOM: Number(process.env.MAX_CLIENTS_PER_ROOM || 8),
  MAX_EVENT_LOOP_DELAY_MS: Number(process.env.MAX_EVENT_LOOP_DELAY_MS || 250),
  MONGODB_URI: (process.env.MONGODB_URI || "").trim(),
  MONGODB_DB_NAME: (process.env.MONGODB_DB_NAME || "bz_games").trim(),
  MONGODB_BUCKET_NAME: (process.env.MONGODB_BUCKET_NAME || "userFiles").trim(),
  MYSQL_HOST: (process.env.MYSQL_HOST || "127.0.0.1").trim(),
  MYSQL_PORT: Number(process.env.MYSQL_PORT || 3306),
  MYSQL_USER: (process.env.MYSQL_USER || "").trim(),
  MYSQL_PASSWORD: process.env.MYSQL_PASSWORD || "",
  MYSQL_DATABASE: (process.env.MYSQL_DATABASE || "bz_games").trim(),
  GITHUB_CLIENT_ID: (process.env.GITHUB_CLIENT_ID || "").trim(),
  GITHUB_CLIENT_SECRET: (process.env.GITHUB_CLIENT_SECRET || "").trim(),
  GITHUB_CALLBACK_URL: (process.env.GITHUB_CALLBACK_URL || "").trim(),
  GITHUB_OAUTH_SCOPE: (process.env.GITHUB_OAUTH_SCOPE || "read:user user:email").trim(),
  SESSION_COOKIE_NAME: (process.env.SESSION_COOKIE_NAME || "bz_games_session").trim(),
  OAUTH_SESSION_TTL_MS: Number(process.env.OAUTH_SESSION_TTL_MS || 30 * 24 * 60 * 60 * 1000),
  OAUTH_STATE_TTL_MS: Number(process.env.OAUTH_STATE_TTL_MS || 10 * 60 * 1000),
};
